import os
import glob
from dbfread import DBF
import pandas as pd
import psycopg2
from psycopg2.extras import execute_values
from functools import reduce





pasta = r"/opt/airflow/scripts/sinan_"
#pasta = r"C:\Users\jesusda\Documents\Sinan_"
padrao_arquivos = os.path.join(pasta, 'chikon*.dbf')

lista_arquivos = glob.glob(padrao_arquivos)

lista_df = []

for arquivo in lista_arquivos:

    tabela = DBF(arquivo, encoding='latin1')  
    df_chikon = pd.DataFrame(iter(tabela))
    
    df_chikon['id_arquivo'] = os.path.basename(arquivo)
    
    lista_df.append(df_chikon)


df_concatenado = pd.concat(lista_df, ignore_index=True)
#df_concatenado = reduce(lambda left, right: pd.merge(left, right, how='outer'), lista_df)
print("Arquivos de chikon lidos", lista_df)

mapeamento_colunas = {
    'ACIDO_PEPT': 'id_pre_existente_acido_peptica',
    'ALRM_ABDOM': 'id_alarme_dor_abdominal',
    'ALRM_HEMAT': 'id_alarme_hematocrito',
    'ALRM_HEPAT': 'id_alarme_hepatomegalia',
    'ALRM_HIPOT': 'id_alarme_hipotensao',
    'ALRM_LETAR': 'id_alarme_letargia',
    'ALRM_LIQ': 'id_alarme_liquidos',
    'ALRM_PLAQ': 'id_alarme_plaquetas',
    'ALRM_SANG': 'id_alarme_sangramento',
    'ALRM_VOM': 'id_alarme_vomitos',
    'ARTRALGIA': 'id_sinal_artralgia',
    'ARTRITE': 'id_sinal_artrite',
    'AUTO_IMUNE': 'id_pre_existente_auto_imunes',
    'CEFALEIA': 'id_sinal_cefaleia',
    'CLASSI_FIN': 'tp_classificacao_final',
    'CLINC_CHIK': 'id_clinc_chik',
    'CODISINF': 'id_distrito_infectado',
    'COMPLICA': 'complica',
    'COMUNINF': 'id_ibge_infectado',
    'CONJUNTVIT': 'id_sinal_conjuntivite',
    'CON_FHD': 'con_fhd',
    'COPAISINF': 'id_pais_infectado',
    'COUFINF': 'id_uf_infectado',
    'CO_BAINF': 'id_bairro_infectado',
    'CRITERIO': 'tp_criterio_confirmacao',
    'CS_ESCOL_N': 'cs_escolaridade_nivel',
    'CS_FLXRET': 'cs_flxret',
    'CS_GESTANT': 'cs_gestante',
    'CS_RACA': 'cs_raca',
    'CS_SEXO': 'cs_sexo',
    'CS_ZONA': 'cs_zona',
    'DDD_HOSP': 'ddd_hospital',
    'DIABETES': 'id_pre_existente_diabetes',
    'DOENCA_TRA': 'doenca_tra',
    'DOR_COSTAS': 'id_sinal_dor_costas',
    'DOR_RETRO': 'id_sinal_dor_retroorbital',
    'DS_OBS': 'ds_obs',
    'DT_ALRM': 'dt_alarme',
    'DT_CHIK_S1': 'dt_chik_soro1',
    'DT_CHIK_S2': 'dt_chik_soro2',
    'DT_DIGITA': 'dt_digita',
    'DT_ENCERRA': 'dt_encerramento',
    'DT_GRAV': 'dt_gravidade',
    'DT_INTERNA': 'dt_interna',
    'DT_INVEST': 'dt_investigacao',
    'DT_NASC': 'dt_nascimento',
    'DT_NOTIFIC': 'dt_notificacao',
    'DT_NS1': 'dt_exame_ns1',
    'DT_OBITO': 'dt_obito',
    'DT_PCR': 'dt_coleta_pcr',
    'DT_PRNT': 'dt_prnt',
    'DT_SIN_PRI': 'dt_sintomas_pri',
    'DT_SORO': 'dt_coleta_dengue',
    'DT_TRANSDM': 'dt_transdm',
    'DT_TRANSRM': 'dt_transrm',
    'DT_TRANSRS': 'dt_transrs',
    'DT_TRANSSE': 'dt_transse',
    'DT_TRANSSM': 'dt_transsm',
    'DT_TRANSUS': 'dt_transus',
    'DT_VIRAL': 'dt_coleta_viral',
    'EPISTAXE': 'epistaxe',
    'EVIDENCIA': 'evidencia',
    'EVOLUCAO': 'id_evolucao',
    'EXANTEMA': 'id_sinal_exantema',
    'FEBRE': 'id_sinal_febre',
    'FLXRECEBI': 'flxrecebi',
    'FONETICA_N': 'fonetica_n',
    'GENGIVO': 'gengivo',
    'GRAV_AST': 'id_grave_ast',
    'GRAV_CONSC': 'id_grave_consciencia',
    'GRAV_CONV': 'id_grave_convergente',
    'GRAV_ENCH': 'id_grave_enchimento',
    'GRAV_EXTRE': 'id_grave_extremidade',
    'GRAV_HEMAT': 'id_grave_hematemese',
    'GRAV_HIPOT': 'id_grave_hipotensao',
    'GRAV_INSUF': 'id_grave_insuficiencia',
    'GRAV_MELEN': 'id_grave_melena',
    'GRAV_METRO': 'id_grave_metrorragia',
    'GRAV_MIOC': 'id_grave_miocardite',
    'GRAV_ORGAO': 'id_grave_orgao',
    'GRAV_PULSO': 'id_grave_pulso',
    'GRAV_SANG': 'id_grave_sangramento_snc',
    'GRAV_TAQUI': 'id_grave_taquicardia',
    'HEMATOLOG': 'id_pre_existente_hematologica',
    'HEMATURA': 'hematura',
    'HEPATOPAT': 'id_pre_existente_hepatopatias',
    'HIPERTENSA': 'id_pre_existente_hipertensao',
    'HISTOPA_N': 'id_resultado_histopatologia',
    'HOSPITAL': 'nm_hospital',
    'HOSPITALIZ': 'id_hospitalizacao',
    'IDENT_MICR': 'ident_micr',
    'ID_AGRAVO': 'id_agravo_cid',
    'ID_BAIRRO': 'id_bairro',
    'ID_CNS_SUS': 'id_cns_sus',
    'ID_DISTRIT': 'id_distrito',
    'ID_GEO1': 'id_geo1',
    'ID_GEO2': 'id_geo2',
    'ID_LOGRADO': 'id_logrado',
    'ID_MN_RESI': 'cd_ibge_paciente',
    'ID_MUNICIP': 'id_municipio',
    'ID_OCUPA_N': 'id_ocupacao',
    'ID_PAIS': 'id_pais',
    'ID_REGIONA': 'id_regional',
    'ID_RG_RESI': 'id_reg_paciente',
    'ID_UNIDADE': 'cd_cnes',
    'IMUNOH_N': 'id_resultado_imunhistoquimica',
    'LACO': 'id_sinal_laco',
    'LACO_N': 'laco_n',
    'LEUCOPENIA': 'id_sinal_leucopenia',
    'MANI_HEMOR': 'mani_hemor',
    'METRO': 'metro',
    'MIALGIA': 'id_sinal_mialgia',
    'MIGRADO_W': 'migrado_w',
    'MUNICIPIO': 'id_ibge_hosp',
    'NAUSEA': 'id_sinal_nausea',
    'NDUPLIC_N': 'nduplic_n',
    'NM_BAIRRO': 'nm_bairro',
    'NM_COMPLEM': 'nm_complem',
    'NM_LOGRADO': 'nm_logrado',
    'NM_MAE_PAC': 'nm_mae_pac',
    'NM_PACIENT': 'nm_pacient',
    'NM_REFEREN': 'nm_referen',
    'NOBAIINF': 'nm_bairro_infectado',
    'NU_ANO': 'nu_ano',
    'NU_CEP': 'nu_cep',
    'NU_DDD_TEL': 'nu_ddd_tel',
    'NU_IDADE_N': 'nu_idade_n',
    'NU_LOTE_H': 'nu_lote_h',
    'NU_LOTE_I': 'nu_lote_i',
    'NU_LOTE_V': 'nu_lote_v',
    'NU_NOTIFIC': 'nu_notificacao',
    'NU_NUMERO': 'nu_numero',
    'NU_TELEFON': 'nu_telefon',
    'PETEQUIAS': 'petequias',
    'PETEQUIA_N': 'id_sinal_petequia',
    'PLAQ_MENOR': 'plaq_menor',
    'PLASMATICO': 'plasmatico',
    'RENAL': 'id_pre_existente_renal',
    'RESUL_NS1': 'id_resultado_ns1',
    'RESUL_PCR_': 'id_resultado_pcr',
    'RESUL_PRNT': 'id_resultado_prnt',
    'RESUL_SORO': 'id_resultado_dengue',
    'RESUL_VI_N': 'id_resultado_viral',
    'RES_CHIKS1': 'id_resultado_chiks1',
    'RES_CHIKS2': 'id_resultado_chiks2',
    'SANGRAM': 'sangram',
    'SEM_NOT': 'sem_notificacao',
    'SEM_PRI': 'sem_sintomas_pri',
    'SG_UF': 'sg_uf',
    'SG_UF_NOT': 'id_uf_ibge',
    'SOROTIPO': 'id_resultado_sorotipo',
    'SOUNDEX': 'soundex',
    'TEL_HOSP': 'tel_hospital',
    'TPAUTOCTO': 'id_autoctone',
    'TP_NOT': 'tp_notificacao',
    'TP_SISTEMA': 'tp_sistema',
    'UF': 'id_uf_hosp',
    'VOMITO': 'id_sinal_vomito'
}

df_concatenado.rename(columns=mapeamento_colunas, inplace=True)
print("Colunas renomeadas")

pasta = r"/opt/airflow/scripts/sinan_"
#pasta = r"C:\Users\jesusda\Documents\Sinan_"
padrao_arquivos_dengue = os.path.join(pasta, 'dengue*.dbf')

lista_arquivos_dengue = glob.glob(padrao_arquivos_dengue)

lista_dengue = []

for arquivo_dengue in lista_arquivos_dengue:

    tabela = DBF(arquivo_dengue, encoding='latin1')  
    df_dengue = pd.DataFrame(iter(tabela))
    
    df_dengue['id_arquivo'] = os.path.basename(arquivo_dengue)
    
    lista_dengue.append(df_dengue)
print("Arquivos de dengue lidos", df_dengue)

df_concatenado_dengue = pd.concat(lista_dengue, ignore_index=True)
#df_concatenado_dengue = reduce(lambda left, right: pd.merge(left, right, how='outer'), lista_dengue)

df_concatenado_dengue.rename(columns=mapeamento_colunas, inplace=True)

df_concatenado = df_concatenado.copy()
df_concatenado['data_carga'] = pd.Timestamp.now()

#CARGA PROD
conn = psycopg2.connect(
    database="db_carga_dados",
    user="user_carga_dados",
    password="C@rgADADOS_Stag3%#4237",
    host="172.20.20.195",
    port="5432"
)

#CARGA DEV
# conn = psycopg2.connect(
#     database="db_dados_tratados",
#     user="user_dados_tratados",
#     password="07bNu$aQxPPz58",
#     host="172.20.21.116",
#     port="5432"
# )

cursor = conn.cursor()
conn.autocommit = False

tabela_destino = 'sinan.chikon_tabela_controle_arquivo'  

cursor.execute(f'TRUNCATE TABLE {tabela_destino}')

colunas = [
    'id_pre_existente_acido_peptica',
    'id_alarme_dor_abdominal',
    'id_alarme_hematocrito',
    'id_alarme_hepatomegalia',
    'id_alarme_hipotensao',
    'id_alarme_letargia',
    'id_alarme_liquidos',
    'id_alarme_plaquetas',
    'id_alarme_sangramento',
    'id_alarme_vomitos',
    'id_sinal_artralgia',
    'id_sinal_artrite',
    'id_pre_existente_auto_imunes',
    'id_sinal_cefaleia',
    'tp_classificacao_final',
    'id_clinc_chik',
    'id_distrito_infectado',
    'complica',
    'id_ibge_infectado',
    'id_sinal_conjuntivite',
    'con_fhd',
    'id_pais_infectado',
    'id_uf_infectado',
    'id_bairro_infectado',
    'tp_criterio_confirmacao',
    'cs_escolaridade_nivel',
    'cs_flxret',
    'cs_gestante',
    'cs_raca',
    'cs_sexo',
    'cs_zona',
    'ddd_hospital',
    'id_pre_existente_diabetes',
    'doenca_tra',
    'id_sinal_dor_costas',
    'id_sinal_dor_retroorbital',
    'ds_obs',
    'dt_alarme',
    'dt_chik_soro1',
    'dt_chik_soro2',
    'dt_digita',
    'dt_encerramento',
    'dt_gravidade',
    'dt_interna',
    'dt_investigacao',
    'dt_nascimento',
    'dt_notificacao',
    'dt_exame_ns1',
    'dt_obito',
    'dt_coleta_pcr',
    'dt_prnt',
    'dt_sintomas_pri',
    'dt_coleta_dengue',
    'dt_transdm',
    'dt_transrm',
    'dt_transrs',
    'dt_transse',
    'dt_transsm',
    'dt_transus',
    'dt_coleta_viral',
    'epistaxe',
    'evidencia',
    'id_evolucao',
    'id_sinal_exantema',
    'id_sinal_febre',
    'flxrecebi',
    'fonetica_n',
    'gengivo',
    'id_grave_ast',
    'id_grave_consciencia',
    'id_grave_convergente',
    'id_grave_enchimento',
    'id_grave_extremidade',
    'id_grave_hematemese',
    'id_grave_hipotensao',
    'id_grave_insuficiencia',
    'id_grave_melena',
    'id_grave_metrorragia',
    'id_grave_miocardite',
    'id_grave_orgao',
    'id_grave_pulso',
    'id_grave_sangramento_snc',
    'id_grave_taquicardia',
    'id_pre_existente_hematologica',
    'hematura',
    'id_pre_existente_hepatopatias',
    'id_pre_existente_hipertensao',
    'id_resultado_histopatologia',
    'nm_hospital',
    'id_hospitalizacao',
    'ident_micr',
    'id_agravo_cid',
    'id_bairro',
    'id_cns_sus',
    'id_distrito',
    'id_geo1',
    'id_geo2',
    'id_logrado',
    'cd_ibge_paciente',
    'id_municipio',
    'id_ocupacao',
    'id_pais',
    'id_regional',
    'id_reg_paciente',
    'cd_cnes',
    'id_resultado_imunhistoquimica',
    'id_sinal_laco',
    'laco_n',
    'id_sinal_leucopenia',
    'mani_hemor',
    'metro',
    'id_sinal_mialgia',
    'migrado_w',
    'id_ibge_hosp',
    'id_sinal_nausea',
    'nduplic_n',
    'nm_bairro',
    'nm_complem',
    'nm_logrado',
    'nm_mae_pac',
    'nm_pacient',
    'nm_referen',
    'nm_bairro_infectado',
    'nu_ano',
    'nu_cep',
    'nu_ddd_tel',
    'nu_idade_n',
    'nu_lote_h',
    'nu_lote_i',
    'nu_lote_v',
    'nu_notificacao',
    'nu_numero',
    'nu_telefon',
    'petequias',
    'id_sinal_petequia',
    'plaq_menor',
    'plasmatico',
    'id_pre_existente_renal',
    'id_resultado_ns1',
    'id_resultado_pcr',
    'id_resultado_prnt',
    'id_resultado_dengue',
    'id_resultado_viral',
    'id_resultado_chiks1',
    'id_resultado_chiks2',
    'sangram',
    'sem_notificacao',
    'sem_sintomas_pri',
    'sg_uf',
    'id_uf_ibge',
    'id_resultado_sorotipo',
    'soundex',
    'tel_hospital',
    'id_autoctone',
    'tp_notificacao',
    'tp_sistema',
    'id_uf_hosp',
    'id_sinal_vomito',
    'id_arquivo',
    'data_carga'
]

# Prepara o comando SQL para inserção
sql_insert = f'''
    INSERT INTO {tabela_destino} ({', '.join(colunas)})
    VALUES ({', '.join(['%s'] * len(colunas))});
'''

for index, row in df_concatenado.iterrows():
    cursor.execute(
        sql_insert,
        (
            row['id_pre_existente_acido_peptica'],
            row['id_alarme_dor_abdominal'],
            row['id_alarme_hematocrito'],
            row['id_alarme_hepatomegalia'],
            row['id_alarme_hipotensao'],
            row['id_alarme_letargia'],
            row['id_alarme_liquidos'],
            row['id_alarme_plaquetas'],
            row['id_alarme_sangramento'],
            row['id_alarme_vomitos'],
            row['id_sinal_artralgia'],
            row['id_sinal_artrite'],
            row['id_pre_existente_auto_imunes'],
            row['id_sinal_cefaleia'],
            row['tp_classificacao_final'],
            row['id_clinc_chik'],
            row['id_distrito_infectado'],
            row['complica'],
            row['id_ibge_infectado'],
            row['id_sinal_conjuntivite'],
            row['con_fhd'],
            row['id_pais_infectado'],
            row['id_uf_infectado'],
            row['id_bairro_infectado'],
            row['tp_criterio_confirmacao'],
            row['cs_escolaridade_nivel'],
            row['cs_flxret'],
            row['cs_gestante'],
            row['cs_raca'],
            row['cs_sexo'],
            row['cs_zona'],
            row['ddd_hospital'],
            row['id_pre_existente_diabetes'],
            row['doenca_tra'],
            row['id_sinal_dor_costas'],
            row['id_sinal_dor_retroorbital'],
            row['ds_obs'],
            row['dt_alarme'],
            row['dt_chik_soro1'],
            row['dt_chik_soro2'],
            row['dt_digita'],
            row['dt_encerramento'],
            row['dt_gravidade'],
            row['dt_interna'],
            row['dt_investigacao'],
            row['dt_nascimento'],
            row['dt_notificacao'],
            row['dt_exame_ns1'],
            row['dt_obito'],
            row['dt_coleta_pcr'],
            row['dt_prnt'],
            row['dt_sintomas_pri'],
            row['dt_coleta_dengue'],
            row['dt_transdm'],
            row['dt_transrm'],
            row['dt_transrs'],
            row['dt_transse'],
            row['dt_transsm'],
            row['dt_transus'],
            row['dt_coleta_viral'],
            row['epistaxe'],
            row['evidencia'],
            row['id_evolucao'],
            row['id_sinal_exantema'],
            row['id_sinal_febre'],
            row['flxrecebi'],
            row['fonetica_n'],
            row['gengivo'],
            row['id_grave_ast'],
            row['id_grave_consciencia'],
            row['id_grave_convergente'],
            row['id_grave_enchimento'],
            row['id_grave_extremidade'],
            row['id_grave_hematemese'],
            row['id_grave_hipotensao'],
            row['id_grave_insuficiencia'],
            row['id_grave_melena'],
            row['id_grave_metrorragia'],
            row['id_grave_miocardite'],
            row['id_grave_orgao'],
            row['id_grave_pulso'],
            row['id_grave_sangramento_snc'],
            row['id_grave_taquicardia'],
            row['id_pre_existente_hematologica'],
            row['hematura'],
            row['id_pre_existente_hepatopatias'],
            row['id_pre_existente_hipertensao'],
            row['id_resultado_histopatologia'],
            row['nm_hospital'],
            row['id_hospitalizacao'],
            row['ident_micr'],
            row['id_agravo_cid'],
            row['id_bairro'],
            row['id_cns_sus'],
            row['id_distrito'],
            row['id_geo1'],
            row['id_geo2'],
            row['id_logrado'],
            row['cd_ibge_paciente'],
            row['id_municipio'],
            row['id_ocupacao'],
            row['id_pais'],
            row['id_regional'],
            row['id_reg_paciente'],
            row['cd_cnes'],
            row['id_resultado_imunhistoquimica'],
            row['id_sinal_laco'],
            row['laco_n'],
            row['id_sinal_leucopenia'],
            row['mani_hemor'],
            row['metro'],
            row['id_sinal_mialgia'],
            row['migrado_w'],
            row['id_ibge_hosp'],
            row['id_sinal_nausea'],
            row['nduplic_n'],
            row['nm_bairro'],
            row['nm_complem'],
            row['nm_logrado'],
            row['nm_mae_pac'],
            row['nm_pacient'],
            row['nm_referen'],
            row['nm_bairro_infectado'],
            row['nu_ano'],
            row['nu_cep'],
            row['nu_ddd_tel'],
            row['nu_idade_n'],
            row['nu_lote_h'],
            row['nu_lote_i'],
            row['nu_lote_v'],
            row['nu_notificacao'],
            row['nu_numero'],
            row['nu_telefon'],
            row['petequias'],
            row['id_sinal_petequia'],
            row['plaq_menor'],
            row['plasmatico'],
            row['id_pre_existente_renal'],
            row['id_resultado_ns1'],
            row['id_resultado_pcr'],
            row['id_resultado_prnt'],
            row['id_resultado_dengue'],
            row['id_resultado_viral'],
            row['id_resultado_chiks1'],
            row['id_resultado_chiks2'],
            row['sangram'],
            row['sem_notificacao'],
            row['sem_sintomas_pri'],
            row['sg_uf'],
            row['id_uf_ibge'],
            row['id_resultado_sorotipo'],
            row['soundex'],
            row['tel_hospital'],
            row['id_autoctone'],
            row['tp_notificacao'],
            row['tp_sistema'],
            row['id_uf_hosp'],
            row['id_sinal_vomito'],
            row['id_arquivo'],
            row['data_carga']
        )
    )

conn.commit()

cursor.close()
conn.close()
print("Carga dengue Realizada")

df_concatenado_dengue = df_concatenado_dengue.copy()
df_concatenado_dengue['data_carga'] = pd.Timestamp.now()

#CARGA PROD
conn = psycopg2.connect(
    database="db_carga_dados",
    user="user_carga_dados",
    password="C@rgADADOS_Stag3%#4237",
    host="172.20.20.195",
    port="5432"
)

#CARGA DEV
# conn = psycopg2.connect(
#     database="db_dados_tratados",
#     user="user_dados_tratados",
#     password="07bNu$aQxPPz58",
#     host="172.20.21.116",
#     port="5432"
# )

cursor = conn.cursor()
conn.autocommit = False

tabela_destino_dengue = 'sinan.dengue_tabela_controle_arquivo'  

cursor.execute(f'TRUNCATE TABLE {tabela_destino_dengue}')

colunas_dengue = [
    'id_pre_existente_acido_peptica',
    'id_alarme_dor_abdominal',
    'id_alarme_hematocrito',
    'id_alarme_hepatomegalia',
    'id_alarme_hipotensao',
    'id_alarme_letargia',
    'id_alarme_liquidos',
    'id_alarme_plaquetas',
    'id_alarme_sangramento',
    'id_alarme_vomitos',
    'id_sinal_artralgia',
    'id_sinal_artrite',
    'id_pre_existente_auto_imunes',
    'id_sinal_cefaleia',
    'tp_classificacao_final',
    'id_clinc_chik',
    'id_distrito_infectado',
    'complica',
    'id_ibge_infectado',
    'id_sinal_conjuntivite',
    'con_fhd',
    'id_pais_infectado',
    'id_uf_infectado',
    'id_bairro_infectado',
    'tp_criterio_confirmacao',
    'cs_escolaridade_nivel',
    'cs_flxret',
    'cs_gestante',
    'cs_raca',
    'cs_sexo',
    'cs_zona',
    'ddd_hospital',
    'id_pre_existente_diabetes',
    'doenca_tra',
    'id_sinal_dor_costas',
    'id_sinal_dor_retroorbital',
    'ds_obs',
    'dt_alarme',
    'dt_chik_soro1',
    'dt_chik_soro2',
    'dt_digita',
    'dt_encerramento',
    'dt_gravidade',
    'dt_interna',
    'dt_investigacao',
    'dt_nascimento',
    'dt_notificacao',
    'dt_exame_ns1',
    'dt_obito',
    'dt_coleta_pcr',
    'dt_prnt',
    'dt_sintomas_pri',
    'dt_coleta_dengue',
    'dt_transdm',
    'dt_transrm',
    'dt_transrs',
    'dt_transse',
    'dt_transsm',
    'dt_transus',
    'dt_coleta_viral',
    'epistaxe',
    'evidencia',
    'id_evolucao',
    'id_sinal_exantema',
    'id_sinal_febre',
    'flxrecebi',
    'fonetica_n',
    'gengivo',
    'id_grave_ast',
    'id_grave_consciencia',
    'id_grave_convergente',
    'id_grave_enchimento',
    'id_grave_extremidade',
    'id_grave_hematemese',
    'id_grave_hipotensao',
    'id_grave_insuficiencia',
    'id_grave_melena',
    'id_grave_metrorragia',
    'id_grave_miocardite',
    'id_grave_orgao',
    'id_grave_pulso',
    'id_grave_sangramento_snc',
    'id_grave_taquicardia',
    'id_pre_existente_hematologica',
    'hematura',
    'id_pre_existente_hepatopatias',
    'id_pre_existente_hipertensao',
    'id_resultado_histopatologia',
    'nm_hospital',
    'id_hospitalizacao',
    'ident_micr',
    'id_agravo_cid',
    'id_bairro',
    'id_cns_sus',
    'id_distrito',
    'id_geo1',
    'id_geo2',
    'id_logrado',
    'cd_ibge_paciente',
    'id_municipio',
    'id_ocupacao',
    'id_pais',
    'id_regional',
    'id_reg_paciente',
    'cd_cnes',
    'id_resultado_imunhistoquimica',
    'id_sinal_laco',
    'laco_n',
    'id_sinal_leucopenia',
    'mani_hemor',
    'metro',
    'id_sinal_mialgia',
    'migrado_w',
    'id_ibge_hosp',
    'id_sinal_nausea',
    'nduplic_n',
    'nm_bairro',
    'nm_complem',
    'nm_logrado',
    'nm_mae_pac',
    'nm_pacient',
    'nm_referen',
    'nm_bairro_infectado',
    'nu_ano',
    'nu_cep',
    'nu_ddd_tel',
    'nu_idade_n',
    'nu_lote_h',
    'nu_lote_i',
    'nu_lote_v',
    'nu_notificacao',
    'nu_numero',
    'nu_telefon',
    'petequias',
    'id_sinal_petequia',
    'plaq_menor',
    'plasmatico',
    'id_pre_existente_renal',
    'id_resultado_ns1',
    'id_resultado_pcr',
    'id_resultado_prnt',
    'id_resultado_dengue',
    'id_resultado_viral',
    'id_resultado_chiks1',
    'id_resultado_chiks2',
    'sangram',
    'sem_notificacao',
    'sem_sintomas_pri',
    'sg_uf',
    'id_uf_ibge',
    'id_resultado_sorotipo',
    'soundex',
    'tel_hospital',
    'id_autoctone',
    'tp_notificacao',
    'tp_sistema',
    'id_uf_hosp',
    'id_sinal_vomito',
    'id_arquivo',
    'data_carga'
]

sql_insert = f'''
    INSERT INTO {tabela_destino_dengue} ({', '.join(colunas_dengue)})
    VALUES %s;
'''

def converter_valor(valor):
    if pd.isnull(valor):
        return None
    elif isinstance(valor, pd.Timestamp):
        return valor.to_pydatetime()
    else:
        return valor

dados_para_inserir = [
    tuple(converter_valor(row[col]) for col in colunas_dengue)
    for index, row in df_concatenado_dengue.iterrows()
]

execute_values(cursor, sql_insert, dados_para_inserir, page_size=10000)

conn.commit()

cursor.close()
conn.close()
print("Carga chikon Realizada")


